---
title: "TestPeakStats"
author: "Davide Rambaldi"
date: "2025-01-16"
output: html_document
---

### SETUP

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = '~/Projects/nf-fragmentomics/devel/peak_stats')
```

```{r}
library(tibble)
library(dplyr)
library(ggplot2)
library(readr)
library(stringr)
library(jsonlite)
setwd("~/Projects/nf-fragmentomics/devel/peak_stats")
```

```{r}
source("../../bin/fragmentomics_peakStats.R")
```

### OPTIONS

```{r}
opt <- list(
  random.points = 10000,
  bg.limit.left = 50,
  bg.limit.right = 50,
  central.coverage.bp = 30,
  signal = "S1",
  target = "T1",
  source = "griffin"
)
```

### TEST MATRIX

Load test matrix:

```{r}
mfile <- "../../tests/input/matrix/CDX2_regions_matrix.gz"
```

```{r}
mdata <- read_matrix(mfile, opt)
```

FFT experiments

```{r}
ggplot() +
  geom_line(data=mdata$summary, aes(x = bin, y = coverage)) +
  ggtitle("Composite coverage")
```

```{r}
fk <- fft(mdata$summary$coverage)
amp <- Mod(fk)
magnitudes <- tibble(magnitudes=amp, bin=mdata$summary$bin)
```

```{r}
ggplot() +
  geom_line(data=magnitudes, aes(x = bin, y = magnitudes))
```


```{r}
reconstructed_signal <- fk
reconstructed_signal[3:length(fk)] <- 0  # Set all components except the first to 0

# Step 3: Inverse FFT to get the time-domain signal
reconstructed_time_signal <- Re(ifft(reconstructed_signal) )

# Step 4: Plot the original and reconstructed signals
plot(1:800, mdata$summary$coverage, type = "l", col = "blue", lwd = 2, ylab = "Amplitude", xlab = "Time", main = "Original vs Reconstructed Signal")
lines(1:800, reconstructed_time_signal, col = "red", lwd = 2)
legend("topright", legend = c("Original Signal", "Reconstructed Signal"), col = c("blue", "red"), lwd = 2)
```


```{r}
write_files(mdata$all, mdata$summary, mdata$stats, opt)
```

```{r}
plot_signal(mdata$summary, mdata$integration, mdata$stats, opt)
```


